### ISSUE TITLE
Dockerized version of this

### ISSUE THREAD

**Issue by ShaunAndersonAZ** [121940kz/Monoprice-Whole-Home-Audio-Android-App-Raspberry-Pi-Server#5]
I created a docker image of this.  I have a limited test environment, but it's currently working great.  I'd like to create a PR to add the Dockerfile to the repo if you're cool with that.

**Comment by 121940kz** [comment]
Sounds good go ahead and initiate a pull request, i'll look the dockerfile over and will approve it. I have no issues with adding the dockerfile to this! Thank you
